### ISSUE TITLE
Warning: Division by zero

### ISSUE THREAD

**Issue by michaelkoper** [FutureMedia/acf-tax#1]
I have a Warning: Division by zero on two locations. Have no idea what it is. When I work locally the plugin doesn't save the checked boxes, and when I tried it now on a remote server I got this message in the admin interface. 

Warning: Division by zero in /theme/acf-tax.php on line 162

Warning: Division by zero in /theme/acf-tax.php on line 168

**Comment by achaido** [comment]
I have a Warning: Division by zero on two locations. Have no idea what it is. When I work locally the plugin doesn't save the checked boxes, and when I tried it now on a remote server I got this message in the admin interface.

Warning: Division by zero in /theme/acf-tax.php on line 162
Warning: Division by zero in /theme/acf-tax.php on line 168

(logged in as friend before, oops)

**Comment by FutureMedia** [comment]
Sorry to hear that. 
The extension worked perfectly in the various installations I used it in the past. It is possible that the last update of the Advanced Custom Fields plugin (2012-8-20) broke things up. In any case, I do not use acf plugin anymore so I'm sorry but I'm not planning to update the extension.

**Comment by achaido** [comment]
No problem. Thanks for your reply! I actually did manage to get it to work
in the end, even with the errors so that's at least something :)

**Comment by ironprogrammer** [comment]
This issue is addressed with my pull request (removes the warning _and_ shows the expected number of tax columns on the edit screen meta box).

**Comment by achaido** [comment]
Yay, that's awesome @ironprogrammer! Thanks a lot. Hope the pull request is accepted.

**Comment by FutureMedia** [comment]
I've already merged acf-tax with Damjan Znidarsic pull. Did you test it?

**Comment by achaido** [comment]
@FutureMedia sorry, I missed that. It works awesomely :) Thanks a lot!

**Comment by ironprogrammer** [comment]
@FutureMedia, Damjan's update addressed issue #2 (the correct checkboxes being ticked on the edit screen), whereas my pull request from a few hours ago specifically addresses the division by zero issue (#1) _and_ fixes the number of columns displayed on the edit screen (#3). Two birds with one stone -- both are fixed with the same code update -- sorry it's split between 2 issues; in retrospect I should have put the pull under #1 ;)

**Comment by FutureMedia** [comment]
Ok Brian,
Thanks for the update.
