### ISSUE TITLE
erroe with ACF 3.4.3

### ISSUE THREAD

**Issue by ghost** [FutureMedia/acf-tax#4]
I installed the last update of ACF (3.4.3) and get this error :

Warning: Invalid argument supplied for foreach() in themes/talm/acf-tax.php on line 346

**Comment by kpoelhekke** [comment]
Same here :(

**Comment by FutureMedia** [comment]
Sorry guys but, unfortunately, I cannot follow the plugin's author updates.

**Comment by kpoelhekke** [comment]
I'm currently figuring out a fix. If i found i'll post it here.. (hopefully today)

**Comment by FutureMedia** [comment]
Ok, thanks.

**Comment by kpoelhekke** [comment]
Overwrite this function:

This works :)

```
function get_value_for_api($post_id, $field)
{

    // format value

    $value = parent::get_value($post_id, $field);

    $term_links = array();
    foreach( $value as $term_id ) {
        $term_id = intval( $term_id );
        $term = get_term( $term_id, $field['taxonomy']);
        $link = get_term_link( $term, $field['taxonomy'] );
        if( !is_wp_error( $link ) )
            $term_links[] = '<a href="' . $link . '" rel="tag">' . $term->name . '</a>';
    }


    if( empty( $term_links ) )
        return false;

    // return value
    return join( '', $term_links ); //$value; 

}
```

**Comment by kpoelhekke** [comment]
Removing the last join and replacing it with 'return $term_links;' will make te function more versatile

**Comment by ghost** [comment]
Hello, and thanks a lot for your fast reply,

I still have the problem, my function is now :

```
function get_value_for_api($post_id, $field)
{

    // format value

    $value = parent::get_value($post_id, $field);

    $term_links = array();
    foreach( $value as $term_id ) {
        $term_id = intval( $term_id );
        $term = get_term( $term_id, $field['taxonomy']);
        $link = get_term_link( $term, $field['taxonomy'] );
        if( !is_wp_error( $link ) )
            $term_links[] = '<a href="' . $link . '" rel="tag">' . $term->name . '</a>';
    }


    if( empty( $term_links ) )
        return false;

    // return value     
    return $term_links;

}
```

**Comment by ghost** [comment]
Sorry for the close !

**Comment by kpoelhekke** [comment]
What is the problem exactly? I'm using the above code and it's working properly...

**Comment by ghost** [comment]
I still have this warning :

Warning: Invalid argument supplied for foreach() in themes/talm/fields/acf-tax.php on line 346

**Comment by kpoelhekke** [comment]
Hmm.. i'll look into it tomorrow. I also still have some problems while using the flexible field type. I'll keep you updated.

**Comment by ghost** [comment]
oups I really apologize, my file was duplicated and I was looking the bad one. Problem solved ! Thanks again.

**Comment by kpoelhekke** [comment]
_like_
