### ISSUE TITLE
tax field doesn't work in repeater field

### ISSUE THREAD

**Issue by kpoelhekke** [FutureMedia/acf-tax#5]
I've updated the following code to make it work:

replace:

if (has_term($term->slug, $term->taxonomy, $post->ID)) {
    $selected = 'checked="checked"';
}

With:

if($field['taxonomy'] == $term->taxonomy && in_array($term->term_id,$field['value'])){
    $selected = 'checked="checked"';
}

**Comment by FutureMedia** [comment]
Ok, thanks kpoelhekke I will update the code. 
Unfortunately, I currently do not use ACF in any of clients sites so I have no way to test it.

**Comment by FutureMedia** [comment]
Ok, updated.
