### ISSUE TITLE
Wrong datatype for second argument

### ISSUE THREAD

**Issue by ghost** [FutureMedia/acf-tax#8]
Hello,
I get this error message after I add the field Tax in Advanced Custom Fields plugin.

"Warning: in_array() [function.in-array]: Wrong datatype for second argument in /themes/test-theme/layouts/acf-tax.php on line 197"

I see the categories but with this error above them.

Any fix I can apply?
Thanks,
Bogdan

**Comment by marcusjwilson** [comment]
Same problem here.  Any resolution?

**Comment by ashworthconsulting** [comment]
**Solution**

Find this:

``` php
if($field['taxonomy'] == $term->taxonomy && in_array($term->term_id, $field['value'])){
    $selected = 'checked="checked"';
}
```

Change it to this:

``` php
if(isset($field['value']) && !empty($field['value'])) {
    if($field['taxonomy'] == $term->taxonomy && in_array($term->term_id, $field['value'])){
        $selected = 'checked="checked"';
    }
}
```

Seems to have worked for me.

This really is a great plugin, but there are other issues as well. Wish further development could happen for this :(
