### ISSUE TITLE
Issue with checkboxes not being what were actually chosen

### ISSUE THREAD

**Issue by ashworthconsulting** [FutureMedia/acf-tax#9]
The thing works with Wordpress, technically, but there's one bug I haven't been able to figure out myself yet in the source. Here's an example:

My checkboxes from taxonomy:

``` text
Item 1
Item 2
Item 3
Item 4
Item 5
```

I'll check the following:

``` text
Item 1  *
Item 2
Item 3  *
Item 4
Item 5
```

Upon reload, none of my chosen selections are kept correctly:

``` text
Item 1
Item 2  *
Item 3
Item 4
Item 5  *
```

Any ideas? Been looking in the code at the update and select functions, but everything seems legit. Something's off, though...or it wouldn't be happening.

**Comment by ashworthconsulting** [comment]
I've managed to come up with a fix, and going to fork + update shortly. Stay tuned everyone! Hopefully it'll be working again soon!

**Comment by FutureMedia** [comment]
Thanks ashworthconsulting.

**Comment by ashworthconsulting** [comment]
Totally! I really needed this plugin, and yours was still mostly there compared to any other option. I wasn't sure if the route I took was the best one in using get_terms() as opposed to ACF core's functions, but what I have there seems right (I think).

ANYONE:
So far seems to be working great, but please let me know if it's behaving oddly and I'd be happy to take a peek. Not sure how often ACF core changes to the point that this could break again, but probably safe for now.

First GitHub fork as well...so if you guys prefer changes structured/submitted differently, happy to adapt my publishing style to suit needs of others  :)

**Comment by ashworthconsulting** [comment]
@FutureMedia - Any objections to me turning this into an actual WordPress plugin and letting it be activated through WordPress, rather than needing to dump code into the theme's functions.php file? I saw that it was listed as "Public Domain", but wanted to be sure you were cool with it before going down that road.

**Comment by FutureMedia** [comment]
Will,

Go ahead, I'll be glad to see this turning in a plugin. Pls. jut keep me as the first developer and the code free and GPL 2. I would suggest you to create an organization so I can be contribute as a member but this is up to you. Pls keep me posted.

Lefteris

**Comment by ashworthconsulting** [comment]
No problem. Thanks for your willingness to keep this going!  :)
